// carbon-experiments-repo

// Hello world program. Does what you think it does.

fn main() -> i32 { // type "i32" is equivalent to int in c/++.
    Print("Hello world"); // no std::cout or printf, just Print(). even better, no packages required
    return 0; // 0 is i32
}

// Functions declared with "fn"

//      fn <fn_name> -> <type> {
//          // code stuff
//      }

// Other note: no multiline comments, sorry